# Generated by Django 5.0.3 on 2024-03-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_to', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'RefCode',
                'verbose_name_plural': 'RefCodes',
            },
        ),
    ]
