# Generated by Django 5.0.3 on 2024-03-22 01:47

import ref_codes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=43)),
                ('is_active', models.BooleanField()),
                ('valid_to', models.DateTimeField(validators=[ref_codes.validators.check_datetime])),
            ],
            options={
                'verbose_name': 'RefCode',
                'verbose_name_plural': 'RefCodes',
            },
        ),
    ]
