# Generated by Django 5.0.3 on 2024-03-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_codes', '0003_alter_refcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refcode',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
